language: cpp
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      env: 
        - TESTS=""
        #- CMAKE_COVERAGE_FLAGS="-O0 -coverage"
        #- CODECOV_TOKEN="99465b5f-26b4-4487-8355-fbcac5249a05"
      before_install:
        - sudo apt-get install gfortran
        - sudo apt-get install mpich libmpich-dev
        - sudo pip install mpi4py
        - sudo pip install numpy
        - sudo pip install -U pytest pytest-cov

install:
  # Make local install build
  - mkdir build
  - cd build
  - cmake -Dtest_codes=ON 
          -DCMAKE_INSTALL_PREFIX=./install 
          -DCMAKE_C_FLAGS="$CMAKE_COVERAGE_FLAGS" 
          -DCMAKE_CXX_FLAGS="$CMAKE_COVERAGE_FLAGS" 
          -DCMAKE_Fortran_FLAGS="$CMAKE_COVERAGE_FLAGS" 
          ..
  - make
  - make install
  - ls
  - ls MDI_QMMM_Driver

#script:
#  - cd ../tests
#  - pytest -vv --cov-report=xml --cov=MDI_Library -k "${TESTS}"

#after_success:
#  # get code coverage
#  - ls -a -l
#  - ls -a -l ../build/MDI_Library/CMakeFiles/mdi.dir
#  - bash <(curl -s https://codecov.io/bash)
